.env:
#  directory: ./some/path
#  filename: .env
#  ignoreIfMalformed: true
#  ignoreIfMissing: false
#  systemProperties: true
#  directory: "./some/path"
  prefix: ""

hello:
  value: ${EXAMPLE_NAME2}
